# Generated by Django 3.0.5 on 2020-04-26 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dominio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OfertaLaboral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oportunidad', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('requisitos', models.TextField()),
                ('tipo', models.CharField(choices=[('Interna', 'Interna'), ('Externa', 'Externa')], default='Interna', max_length=7)),
                ('vigencia', models.DateTimeField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Area')),
                ('dominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Dominio')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Localidad')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Nivel')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_add', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_edit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
