# Generated by Django 3.0.5 on 2020-05-05 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200505_0057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'permissions': (('listar_areas', 'Listar areas'), ('crear_area', 'Agregar area'), ('editar_area', 'Editar area'), ('eliminar_area', 'Eliminar area'))},
        ),
        migrations.AlterModelOptions(
            name='dominio',
            options={'permissions': (('listar_dominios', 'Listar dominios'), ('crear_dominio', 'Agregar dominio'), ('editar_dominio', 'Editar dominio'), ('eliminar_dominio', 'Eliminar dominio'))},
        ),
        migrations.AlterModelOptions(
            name='localidad',
            options={'permissions': (('listar_localidades', 'Listar localidades'), ('crear_localidad', 'Agregar localidad'), ('editar_localidad', 'Editar localidad'), ('eliminar_localidad', 'Eliminar localidad'))},
        ),
        migrations.AlterModelOptions(
            name='nivel',
            options={'permissions': (('listar_niveles', 'Listar niveles'), ('crear_nivel', 'Agregar nivel'), ('editar_nivel', 'Editar nivel'), ('eliminar_nivel', 'Eliminar nivel'))},
        ),
        migrations.AlterModelOptions(
            name='ofertalaboral',
            options={'permissions': (('listar_ofertalaboral', 'Listar ofertas laborales'), ('crear_ofertalaboral', 'Agregar oferta laboral'), ('editar_ofertalaboral', 'Editar oferta laboral'), ('eliminar_ofertalaboral', 'Eliminar oferta laboral'))},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'permissions': (('editar_persona', 'Editar datos personales'),)},
        ),
    ]
