# Generated by Django 3.0.5 on 2020-05-05 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_auto_20200505_1719'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OfertaLaboral',
            new_name='Empleo',
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_postulacion', models.DateField()),
                ('empleo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Empleo')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Persona')),
            ],
            options={
                'permissions': (('listar_postulaciones', 'Listar postulaciones'), ('crear_postulacion', 'Agregar postulacion'), ('editar_postulacion', 'Editar postulacion'), ('eliminar_postulacion', 'Eliminar postulacion')),
            },
        ),
    ]
