# Generated by Django 3.0.5 on 2020-05-05 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200505_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleo',
            options={'permissions': (('listar_empleos', 'Listar empleos'), ('crear_empleo', 'Agregar empleo'), ('editar_empleo', 'Editar empleo'), ('eliminar_empleo', 'Eliminar empleo'))},
        ),
    ]
