# Generated by Django 3.0.5 on 2020-05-05 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200505_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'permissions': (('api_listar_areas', 'Listar areas'), ('api_crear_area', 'Agregar area'), ('api_editar_area', 'Editar area'), ('api_eliminar_area', 'Eliminar area'))},
        ),
        migrations.AlterModelOptions(
            name='dominio',
            options={'permissions': (('api_listar_dominios', 'Listar dominios'), ('api_crear_dominio', 'Agregar dominio'), ('api_editar_dominio', 'Editar dominio'), ('api_eliminar_dominio', 'Eliminar dominio'))},
        ),
        migrations.AlterModelOptions(
            name='empleo',
            options={'permissions': (('api_listar_empleos', 'Listar empleos'), ('api_crear_empleo', 'Agregar empleo'), ('api_editar_empleo', 'Editar empleo'), ('api_eliminar_empleo', 'Eliminar empleo'))},
        ),
        migrations.AlterModelOptions(
            name='localidad',
            options={'permissions': (('api_listar_localidades', 'Listar localidades'), ('api_crear_localidad', 'Agregar localidad'), ('api_editar_localidad', 'Editar localidad'), ('api_eliminar_localidad', 'Eliminar localidad'))},
        ),
        migrations.AlterModelOptions(
            name='nivel',
            options={'permissions': (('api_listar_niveles', 'Listar niveles'), ('api_crear_nivel', 'Agregar nivel'), ('api_editar_nivel', 'Editar nivel'), ('api_eliminar_nivel', 'Eliminar nivel'))},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'permissions': (('api_editar_persona', 'Editar datos personales'),)},
        ),
        migrations.AlterModelOptions(
            name='postulacion',
            options={'permissions': (('api_listar_postulaciones', 'Listar postulaciones'), ('api_crear_postulacion', 'Agregar postulacion'), ('api_editar_postulacion', 'Editar postulacion'), ('api_eliminar_postulacion', 'Eliminar postulacion'))},
        ),
    ]
