# Generated by Django 3.0.5 on 2020-05-06 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200506_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='ultima_modificacion',
            field=models.DateField(null=True),
        ),
    ]
