# Generated by Django 3.0.5 on 2020-05-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_persona_ultima_modificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='ultima_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
