# Generated by Django 3.0.5 on 2020-05-06 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200506_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='ultima_modificacion',
        ),
    ]
