# Generated by Django 3.0.5 on 2020-05-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_persona_ultima_modificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='ultima_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
