# Generated by Django 3.0.5 on 2020-05-06 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0012_persona_ultima_modificacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dominio',
            options={},
        ),
        migrations.AlterModelOptions(
            name='empleo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='localidad',
            options={},
        ),
        migrations.AlterModelOptions(
            name='nivel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={},
        ),
        migrations.AlterModelOptions(
            name='postulacion',
            options={},
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('parentesco', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(max_length=50)),
                ('habla', models.CharField(choices=[('B', 'B'), ('I', 'I'), ('A', 'A'), ('N', 'N')], default='B', max_length=1)),
                ('lee', models.CharField(choices=[('B', 'B'), ('I', 'I'), ('A', 'A'), ('N', 'N')], default='B', max_length=1)),
                ('escribe', models.CharField(choices=[('B', 'B'), ('I', 'I'), ('A', 'A'), ('N', 'N')], default='B', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(max_length=200)),
                ('rubro', models.CharField(max_length=100)),
                ('puesto', models.CharField(max_length=100)),
                ('trabajando', models.BooleanField(default=False)),
                ('desde', models.CharField(max_length=20)),
                ('hasta', models.CharField(max_length=20, null=True)),
                ('tareas', models.TextField()),
                ('superior_nombre', models.CharField(max_length=200)),
                ('superior_puesto', models.CharField(max_length=200)),
                ('superior_contacto', models.CharField(max_length=200)),
                ('documento', models.TextField()),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(max_length=200)),
                ('titulo', models.CharField(max_length=200)),
                ('nivel', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=50)),
                ('estudiando', models.BooleanField(default=False)),
                ('desde', models.CharField(max_length=20)),
                ('hasta', models.CharField(max_length=20, null=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
