# Generated by Django 3.0.5 on 2020-05-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200506_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='educacion',
            name='documento',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
