# Generated by Django 3.0.5 on 2020-05-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_educacion_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educacion',
            name='hasta',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='hasta',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
