# Generated by Django 3.0.5 on 2020-05-09 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0015_auto_20200508_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulacion',
            name='persona',
        ),
        migrations.AddField(
            model_name='postulacion',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='fecha_postulacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
