# Generated by Django 3.0.5 on 2020-05-09 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200509_1936'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Postulacion',
        ),
    ]
