# Generated by Django 3.0.5 on 2020-05-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200509_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulacionempleo',
            name='empleo',
        ),
        migrations.AddField(
            model_name='empleo',
            name='postulaciones',
            field=models.ManyToManyField(blank=True, null=True, to='api.PostulacionEmpleo'),
        ),
    ]
