# Generated by Django 3.0.5 on 2020-05-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20200510_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleo',
            name='postulaciones',
            field=models.ManyToManyField(to='api.PostulacionEmpleo'),
        ),
    ]
