# Generated by Django 3.0.5 on 2020-05-21 11:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0023_auto_20200510_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=10)),
                ('tag_user', models.ManyToManyField(related_name='tagss', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
