# Generated by Django 3.0.5 on 2020-05-21 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag_user',
            new_name='user_tag',
        ),
    ]
