# Generated by Django 3.0.5 on 2020-05-22 19:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0025_auto_20200521_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='user_tag',
            field=models.ManyToManyField(related_name='tags', to=settings.AUTH_USER_MODEL),
        ),
    ]
