# Generated by Django 3.0.5 on 2020-05-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20200522_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='estado',
            field=models.CharField(choices=[('Ingresado', 'Ingresado'), ('Visto', 'Visto'), ('Seleccionado', 'Seleccionado'), ('Contratado', 'Contratado')], default='Ingresado', max_length=20),
        ),
    ]
