# Generated by Django 3.0.5 on 2020-05-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_persona_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleo',
            name='codigo',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
