# Generated by Django 3.0.5 on 2020-05-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_empleo_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleo',
            name='vigencia',
            field=models.DateField(),
        ),
    ]
