# Generated by Django 3.0.5 on 2020-05-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20200523_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleo',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, default=None),
            preserve_default=False,
        ),
    ]
