# Generated by Django 3.0.5 on 2020-05-23 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20200523_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
